HW_7. Add light theme
Atikingi/skyprofy-ts pull request #7
Opened 2022-09-19 20:58 UTC by Atikingi

Сделана 7я домашняя работа https://skyengpublic.notion.site/5-7-Context-376cdb55aca1441ca30ff6af2e3ebcc9

Добавлен переключатель на светлую/темную тему.
Реализована светлая тема.

2022-09-20 06:41 UTC, mrerberg commented
public/img/icon/light.svg

Сделай иконку компонентом. Ты же можешь влиять на цвет svg через пропсы (fill, stroke), посредством currentColor. Иконка то одна, она просто цвет меняет

2022-09-20 06:55 UTC, mrerberg commented
Почему нельзя настраивать звук, когда музыка выключена? Это неочевидно

2022-09-20 06:56 UTC, mrerberg commented
Может быть загвоздка по звуку тут

```
const onVolumeChange = (e: React.ChangeEvent) => {
    audioRef.current.volume = Number((e.target as HTMLInputElement).value);
    setIsVolumeOn(true);
  };
```

Есть смысл делать апдейт     setIsVolumeOn(true); тогда, когда музыка 100% выключена. А так ты каждый раз при изменении звука выываешь     setIsVolumeOn(true);

2022-09-20 06:57 UTC, mrerberg requested changes

2022-09-20 06:57 UTC, mrerberg commented on src/components/main/center-block/playlist/playlist-item/track-author/style.ts
> +  color: ${props => props.isDarkTheme ? COLORS['track-link-dark'] : COLORS['track-link-light']};
Вообще, можно сделать хитрее. Использовать просто вместо значения переменную var(--some-var), а контекст бы просто подменял значения этих переменных

2022-09-20 18:35 UTC, Atikingi commented on src/components/main/center-block/playlist/playlist-item/track-author/style.ts
> +  color: ${props => props.isDarkTheme ? COLORS['track-link-dark'] : COLORS['track-link-light']};
Сделал не глобально, но с использованием переменных

2022-09-21 06:25 UTC, mrerberg requested changes

2022-09-21 06:25 UTC, mrerberg commented on src/components/bar/player-controls/index.tsx
> +          <SvgImage href='/skyprofy-ts/img/icon/sprite.svg#icon-shuffle' ariaLabel="shuffle" />
Сделай иконки отдельными компоненты, не нужно использовать спрайт

https://github.com/core-ds/icons/blob/master/packages/android/src/AlfaScoresMIcon.tsx

2022-09-21 10:10 UTC, Atikingi commented on src/components/bar/player-controls/index.tsx
> +          <SvgImage href='/skyprofy-ts/img/icon/sprite.svg#icon-shuffle' ariaLabel="shuffle" />
Переделал

2022-09-22 07:31 UTC, mrerberg approved these changes

2022-09-22 07:31 UTC, mrerberg commented on src/components/icons/darkThemeIcon.tsx
> +const DarkThemeIcon = () => {
Зачем тебе данная иконка, если подойдет 1? Ты все через currentColor делаешь

2022-09-22 07:45 UTC, Atikingi commented on src/components/icons/darkThemeIcon.tsx
> +const DarkThemeIcon = () => {
Там разные иконки. Когда темная тема одна, потом другая. Меняется не только цвет

2022-09-24 11:41 UTC, merged